---
- name: Install and start httpd
  hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and enable httpd
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    - name: Deploy index.html file
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "<h1> Deployed via Ansible </h1>"
