# variable -> dynamic value assignment
---
- name: Install and start LEMP stack with variable
  hosts: localhost
  become: true

  vars:
    web_pkg: nginx
    database_pkg: mariadb105-server
    php_pkg:
      - php
      - php-fpm
      - php-mysqlnd
    
    web_service: nginx
    database_service: mariadb
    php_service: php-fpm
    web_root: /usr/share/nginx/html/index.php
  
  tasks:
    # - name: Stopped httpd        # httpd is stopped that previously installed
    #   ansible.builtin.systemd:
    #     name: httpd
    #     state: stopped

    - name: Install nginx      # install nginx 
      ansible.builtin.dnf:
        name: "{{ web_pkg }}"
        state: present

    - name: Install MariaDB server
      ansible.builtin.dnf:
        name: "{{ database_pkg }}"
        state: present

    - name: Install PHP and modules
      ansible.builtin.dnf:
        name: "{{php_pkg}}"
        state: present

    - name: Start and enable nginx
      ansible.builtin.systemd:
        name: "{{ web_service }}"
        state: started
        enabled: true

    - name: Start and enable MariaDB
      ansible.builtin.systemd:
        name: "{{ database_service }}"
        state: started
        enabled: true

    - name: start and enable php-fpm
      ansible.builtin.systemd:
        name: "{{ php_service }}"
        state: started
        enabled: true

    - name: Deploy index.php file
      ansible.builtin.copy:
        dest: "{{ web_root }}"
        content: "<?php phpinfo(); ?>"
